"""add_geotagging_inline_video

Revision ID: 01472f00acb3
Revises: 6f95102f8e2f
Create Date: 2026-05-11 08:59:38.996189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01472f00acb3'
down_revision: Union[str, Sequence[str], None] = '6f95102f8e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('entries', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('entries', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('media', sa.Column('is_inline', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.create_table(
        'video_notes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('entry_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('storage_path', sa.String(), nullable=False),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('thumbnail_path', sa.String(), nullable=True),
        sa.Column('transcription', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_notes')
    op.drop_column('media', 'is_inline')
    op.drop_column('entries', 'location_name')
    op.drop_column('entries', 'longitude')
    op.drop_column('entries', 'latitude')
    # ### end Alembic commands ###
