"""add_entry_encryption_fields_and_revisions

Revision ID: 6f95102f8e2f
Revises: 9a0e94a40c33
Create Date: 2026-05-11 08:46:18.700909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f95102f8e2f"
down_revision: Union[str, Sequence[str], None] = "9a0e94a40c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entries",
        sa.Column("is_encrypted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column("entries", sa.Column("encrypted_at", sa.DateTime(), nullable=True))
    op.create_table(
        "entry_revisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("mood", sa.String(length=50), nullable=True),
        sa.Column("snapshot_reason", sa.String(length=20), server_default="edit", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("entry_id", "revision_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_revisions")
    op.drop_column("entries", "encrypted_at")
    op.drop_column("entries", "is_encrypted")
    # ### end Alembic commands ###
